name: tabby_flutter_inapp_sdk
description: Tabby Flutter SDK
version: 1.2.0
homepage: https://github.com/tabby-ai/tabby_flutter_inapp_sdk

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Remote API
  http: ^0.13.4

  # Webview
  flutter_inappwebview: ^5.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.21.1
flutter:
  assets:
    - assets/images/tabby-badge.png
    - assets/images/2.0x/tabby-badge.png
    - assets/images/3.0x/tabby-badge.png
    - assets/images/r1.jpg
    - assets/images/r2.jpg
    - assets/images/r3.jpg
    - assets/images/r4.jpg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial-Regular.ttf
          weight: 500
